const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {Pool}=require('pg');
const ExcelJS=require('exceljs');
const app=express();
app.set('trust proxy',1);
app.use(express.json({limit:'1mb'}));
const PUBLIC_DIR=path.join(__dirname,'public');
app.use(express.static(PUBLIC_DIR));
// Explicit root route for hosted deployments (Render, Railway, etc.).
app.get('/',(req,res)=>res.sendFile(path.join(PUBLIC_DIR,'index.html')));

// V6 storage: PostgreSQL when DATABASE_URL is set; safe local JSON fallback for desktop testing.
const LOCAL_DB=path.join(__dirname,'data.json');
let local={leagues:{}}; try{local=JSON.parse(fs.readFileSync(LOCAL_DB,'utf8'))}catch{}
const pg=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false}}):null;
async function initDB(){if(pg){
  await pg.query(`CREATE TABLE IF NOT EXISTS leagues (id TEXT PRIMARY KEY, data JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await pg.query(`CREATE TABLE IF NOT EXISTS accounts (username TEXT PRIMARY KEY, display_name TEXT NOT NULL, salt TEXT NOT NULL, password_hash TEXT NOT NULL, session_hash TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await pg.query(`CREATE TABLE IF NOT EXISTS memberships (account_id TEXT NOT NULL REFERENCES accounts(username) ON DELETE CASCADE, league_id TEXT NOT NULL, player_name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'player', joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(account_id,league_id))`);
}else{local.accounts=local.accounts||{};local.memberships=local.memberships||[]}}
async function getLeague(id){if(!pg)return local.leagues[id]||null;const r=await pg.query('SELECT data FROM leagues WHERE id=$1',[id]);return r.rows[0]?.data||null}
async function putLeague(id,l){if(!pg){local.leagues[id]=l;fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2));return}await pg.query(`INSERT INTO leagues(id,data,updated_at) VALUES($1,$2::jsonb,NOW()) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW()`,[id,JSON.stringify(l)])}

const sha=s=>crypto.createHash('sha256').update(String(s||'')).digest('hex');
const token=()=>crypto.randomBytes(24).toString('hex');
const fallbackW3=[['ATL','GB','2026-09-24T20:15:00-04:00'],['LAC','BUF','2026-09-27T13:00:00-04:00'],['CAR','CLE','2026-09-27T13:00:00-04:00'],['NYJ','DET','2026-09-27T13:00:00-04:00'],['HOU','IND','2026-09-27T13:00:00-04:00'],['NE','JAX','2026-09-27T13:00:00-04:00'],['KC','MIA','2026-09-27T13:00:00-04:00'],['TEN','NYG','2026-09-27T13:00:00-04:00'],['CIN','PIT','2026-09-27T13:00:00-04:00'],['SEA','WAS','2026-09-27T13:00:00-04:00'],['ARI','SF','2026-09-27T16:05:00-04:00'],['MIN','TB','2026-09-27T16:05:00-04:00'],['LV','NO','2026-09-27T16:25:00-04:00'],['BAL','DAL','2026-09-27T16:25:00-04:00'],['LAR','DEN','2026-09-27T20:20:00-04:00'],['PHI','CHI','2026-09-28T20:15:00-04:00']].map((x,i)=>({id:'2026-w3-'+i,away:x[0],home:x[1],kickoff:x[2],status:'scheduled',winner:null,awayScore:null,homeScore:null}));
const cache={}; async function schedule(week){if(cache[week]&&Date.now()-cache[week].at<15000)return cache[week].games;try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?dates=2026&seasontype=2&week=${week}`,{signal:AbortSignal.timeout(5000)});if(!r.ok)throw 0;const j=await r.json();const games=j.events.map(e=>{const c=e.competitions[0],a=c.competitors.find(x=>x.homeAway==='away'),h=c.competitors.find(x=>x.homeAway==='home');let winner=null;if(c.status.type.completed)winner=(+a.score>+h.score)?a.team.abbreviation:h.team.abbreviation;return{id:e.id,away:a.team.abbreviation,home:h.team.abbreviation,kickoff:e.date,status:c.status.type.name,statusDetail:c.status.type.detail||c.status.type.shortDetail||'',clock:c.status.displayClock||'',period:c.status.period||0,winner,awayScore:a.score,homeScore:h.score}});cache[week]={at:Date.now(),games};return games}catch(e){return week===3?fallbackW3:[]}}
const adminOK=(l,p)=>sha(p)===l.adminHash; const auth=(l,name,t)=>l?.users?.[name]&&l.users[name].tokenHash===sha(t);
const route=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const uname=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9_.-]/g,'').slice(0,32);
const passHash=(password,salt)=>crypto.scryptSync(String(password),salt,64).toString('hex');
async function getAccount(username){username=uname(username);if(!pg)return local.accounts?.[username]||null;const r=await pg.query('SELECT * FROM accounts WHERE username=$1',[username]);return r.rows[0]||null}
async function saveAccount(a){if(!pg){local.accounts=local.accounts||{};local.accounts[a.username]=a;fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2));return}await pg.query(`INSERT INTO accounts(username,display_name,salt,password_hash,session_hash) VALUES($1,$2,$3,$4,$5) ON CONFLICT(username) DO UPDATE SET display_name=EXCLUDED.display_name,salt=EXCLUDED.salt,password_hash=EXCLUDED.password_hash,session_hash=EXCLUDED.session_hash`,[a.username,a.display_name,a.salt,a.password_hash,a.session_hash])}
async function accountByToken(t){if(!t)return null;const h=sha(t);if(!pg){return Object.values(local.accounts||{}).find(a=>a.session_hash===h)||null}const r=await pg.query('SELECT * FROM accounts WHERE session_hash=$1',[h]);return r.rows[0]||null}
async function addMembership(accountId,leagueId,playerName,role='player'){if(!pg){local.memberships=local.memberships||[];let m=local.memberships.find(x=>x.account_id===accountId&&x.league_id===leagueId);if(m){m.player_name=playerName;m.role=role==='commissioner'?'commissioner':m.role}else local.memberships.push({account_id:accountId,league_id:leagueId,player_name:playerName,role,joined_at:new Date().toISOString()});fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2));return}await pg.query(`INSERT INTO memberships(account_id,league_id,player_name,role) VALUES($1,$2,$3,$4) ON CONFLICT(account_id,league_id) DO UPDATE SET player_name=EXCLUDED.player_name,role=CASE WHEN memberships.role='commissioner' THEN 'commissioner' ELSE EXCLUDED.role END`,[accountId,leagueId,playerName,role])}
async function getMemberships(accountId){if(!pg)return (local.memberships||[]).filter(x=>x.account_id===accountId);const r=await pg.query('SELECT * FROM memberships WHERE account_id=$1 ORDER BY joined_at DESC',[accountId]);return r.rows}

// V7.3 global account + My Pools API. Existing pool data stays untouched.
app.post('/api/account/register',route(async(req,res)=>{const username=uname(req.body.username),display=String(req.body.displayName||'').trim().slice(0,40),password=String(req.body.password||'');if(username.length<3||!display||password.length<6)return res.status(400).json({error:'Username must be 3+ characters, display name is required, and password must be 6+ characters.'});if(await getAccount(username))return res.status(409).json({error:'That username is already taken.'});const salt=crypto.randomBytes(16).toString('hex'),t=token(),a={username,display_name:display,salt,password_hash:passHash(password,salt),session_hash:sha(t),created_at:new Date().toISOString()};await saveAccount(a);res.json({username,displayName:display,token:t})}));
app.post('/api/account/login',route(async(req,res)=>{const username=uname(req.body.username),password=String(req.body.password||''),a=await getAccount(username);if(!a||!crypto.timingSafeEqual(Buffer.from(a.password_hash,'hex'),Buffer.from(passHash(password,a.salt),'hex')))return res.status(403).json({error:'Incorrect username or password.'});const t=token();a.session_hash=sha(t);await saveAccount(a);res.json({username:a.username,displayName:a.display_name,token:t})}));
app.get('/api/account/me',route(async(req,res)=>{const a=await accountByToken(req.query.token);if(!a)return res.status(401).json({error:'Please sign in.'});const ms=await getMemberships(a.username),pools=[];for(const m of ms){const l=await getLeague(m.league_id);if(l)pools.push({id:m.league_id,name:l.name,playerName:m.player_name,role:m.role,season:l.season||2026,modes:{...DEFAULT_MODES,...(l.poolModes||{})}})}res.json({username:a.username,displayName:a.display_name,pools})}));
app.post('/api/account/pools/:id/join',route(async(req,res)=>{const a=await accountByToken(req.body.accountToken),l=await getLeague(req.params.id);if(!a)return res.status(401).json({error:'Please sign in to your Fourth & Pick account.'});if(!l)return res.status(404).json({error:'Pool not found.'});const name=a.display_name;let u=l.users[name];if(u&&u.pinHash){const pp=String(req.body.playerPin||''),legacyOK=String(req.body.legacyName||'')===name&&auth(l,name,req.body.legacyToken);if(!legacyOK&&(!pp||u.pinHash!==sha(pp)))return res.status(409).json({error:'A player with your display name already exists in this pool. Enter that player’s old pool PIN once to claim the membership.'})}const t=token();if(!u)u=l.users[name]={picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};u.tokenHash=sha(t);await putLeague(req.params.id,l);await addMembership(a.username,req.params.id,name,'player');res.json({id:req.params.id,name,token:t})}));
app.post('/api/account/pools/:id/open',route(async(req,res)=>{const a=await accountByToken(req.body.accountToken);if(!a)return res.status(401).json({error:'Please sign in.'});const ms=await getMemberships(a.username),m=ms.find(x=>x.league_id===req.params.id);if(!m)return res.status(403).json({error:'You are not a member of this pool.'});const l=await getLeague(req.params.id);if(!l)return res.status(404).json({error:'Pool not found.'});const t=token();if(!l.users[m.player_name])return res.status(409).json({error:'Your pool membership needs to be rejoined.'});l.users[m.player_name].tokenHash=sha(t);await putLeague(req.params.id,l);res.json({id:req.params.id,name:m.player_name,token:t,role:m.role})}));

app.post('/api/leagues',route(async(req,res)=>{const id=crypto.randomBytes(4).toString('hex'),pin=String(req.body.pin||'').trim(),owner=String(req.body.owner||'').trim().slice(0,40),playerPin=String(req.body.playerPin||'').trim();if(pin.length<4||!owner||playerPin.length<4)return res.status(400).json({error:'Pool name, your name, commissioner PIN and player PIN (4+ chars) are required.'});const l={name:String(req.body.name||'Fourth & Pick').trim().slice(0,60),season:2026,adminHash:sha(pin),users:{},manualResults:{},createdAt:new Date().toISOString()};const t=token();l.users[owner]={pinHash:sha(playerPin),tokenHash:sha(t),picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};await putLeague(id,l);const acct=await accountByToken(req.body.accountToken);if(acct)await addMembership(acct.username,id,owner,'commissioner');res.json({id,name:owner,token:t})}));
app.post('/api/leagues/:id/auth',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.status(404).json({error:'Pool not found'});const name=String(req.body.name||'').trim().slice(0,40),pin=String(req.body.pin||'').trim();if(!name||pin.length<4)return res.status(400).json({error:'Name and 4+ character player PIN required.'});let u=l.users[name];if(u&&u.pinHash&&u.pinHash!==sha(pin))return res.status(403).json({error:'That name is already registered with a different PIN.'});const t=token();if(!u)u=l.users[name]={picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};u.pinHash=sha(pin);u.tokenHash=sha(t);await putLeague(req.params.id,l);res.json({name,token:t})}));
app.get('/api/leagues/:id',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.status(404).json({error:'Pool not found'});const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();const viewer=String(req.query.name||''),ok=auth(l,viewer,req.query.token);const users={};for(const [n,u] of Object.entries(l.users)){const picks={};for(const g of games){const locked=Date.parse(g.kickoff)<=now;if((n===viewer&&ok)||locked)picks[g.id]=u.picks?.[g.id]||null}users[n]={picks,tiebreaker:(n===viewer&&ok||games.every(g=>Date.parse(g.kickoff)<=now))?u.tiebreakers?.[week]??null:null}}res.json({id:req.params.id,name:l.name,season:l.season,week,games:games.map(g=>({...g,winner:l.manualResults[g.id]||g.winner,locked:Date.parse(g.kickoff)<=now})),users,viewer:ok?viewer:null})}));
app.post('/api/leagues/:id/picks',route(async(req,res)=>{const l=await getLeague(req.params.id),name=String(req.body.name||'');if(!l)return res.sendStatus(404);if(!auth(l,name,req.body.token))return res.status(403).json({error:'Please sign in again.'});const week=Math.max(1,Math.min(18,+req.body.week||3)),games=await schedule(week),byId=Object.fromEntries(games.map(g=>[g.id,g])),now=Date.now();for(const [gid,pick] of Object.entries(req.body.picks||{})){const g=byId[gid];if(g&&Date.parse(g.kickoff)>now&&[g.away,g.home].includes(pick))l.users[name].picks[gid]=pick}if(games.some(g=>Date.parse(g.kickoff)>now))l.users[name].tiebreakers[week]=Math.max(0,Math.min(150,+req.body.tiebreaker||0));await putLeague(req.params.id,l);res.json({ok:true})}));
app.post('/api/leagues/:id/results',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});for(const [gid,w] of Object.entries(req.body.results||{})){if(w)l.manualResults[gid]=w;else delete l.manualResults[gid]}await putLeague(req.params.id,l);res.json({ok:true})}));
app.get('/api/leagues/:id/standings',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const weeks=await Promise.all(Array.from({length:18},(_,i)=>schedule(i+1))),rows=[];for(const [name,u] of Object.entries(l.users)){let wins=0,losses=0,pending=0;const weekly={};for(let wi=0;wi<18;wi++){let w=0,lo=0;for(const g of weeks[wi]){const win=l.manualResults[g.id]||g.winner,p=u.picks?.[g.id];if(!p)continue;if(!win){pending++;continue}p===win?w++:lo++}weekly[wi+1]={wins:w,losses:lo};wins+=w;losses+=lo}rows.push({name,wins,losses,pending,pct:wins+losses?wins/(wins+losses):0,weekly})}rows.sort((a,b)=>b.wins-a.wins||a.losses-b.losses||a.name.localeCompare(b.name));res.json(rows)}));
async function exportData(l){const weeks=await Promise.all(Array.from({length:18},(_,i)=>schedule(i+1))),games=weeks.flat(),rows=[];for(const [name,u] of Object.entries(l.users)){let w=0,lo=0;for(const g of games){const win=l.manualResults[g.id]||g.winner,p=u.picks?.[g.id];if(win&&p)(p===win?w++:lo++)}rows.push({name,w,lo,pct:w+lo?100*w/(w+lo):0,picks:games.map(g=>u.picks?.[g.id]||'')})}return {games,rows}}
app.get('/api/leagues/:id/export.csv',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const {games,rows}=await exportData(l);const out=[['Player','Wins','Losses','Win %',...games.map(g=>`${g.away}@${g.home}`)],...rows.map(r=>[r.name,r.w,r.lo,r.w+r.lo?r.pct.toFixed(1)+'%':'',...r.picks])];res.setHeader('Content-Disposition',`attachment; filename="${l.name.replace(/[^a-z0-9]/gi,'_')}_2026.csv"`);res.type('text/csv').send(out.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'))}));
app.get('/api/leagues/:id/export.xlsx',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const {games,rows}=await exportData(l),wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Season Picks');ws.addRow(['Player','Wins','Losses','Win %',...games.map(g=>`${g.away}@${g.home}`)]);for(const r of rows)ws.addRow([r.name,r.w,r.lo,r.w+r.lo?r.pct/100:null,...r.picks]);ws.getRow(1).font={bold:true};ws.views=[{state:'frozen',xSplit:1,ySplit:1}];ws.columns.forEach(c=>c.width=Math.min(24,Math.max(10,...c.values.slice(1).map(v=>String(v??'').length+2))));ws.getColumn(4).numFmt='0.0%';const summary=wb.addWorksheet('Leaderboard');summary.addRow(['Player','Wins','Losses','Win %']);rows.sort((a,b)=>b.w-a.w||a.lo-b.lo||a.name.localeCompare(b.name)).forEach(r=>summary.addRow([r.name,r.w,r.lo,r.w+r.lo?r.pct/100:null]));summary.getRow(1).font={bold:true};summary.getColumn(4).numFmt='0.0%';summary.columns.forEach(c=>c.width=18);res.setHeader('Content-Disposition',`attachment; filename="${l.name.replace(/[^a-z0-9]/gi,'_')}_2026.xlsx"`);res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');await wb.xlsx.write(res);res.end()}));
app.get('/api/leagues/:id/week-summary',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();const rows=[];for(const [name,u] of Object.entries(l.users)){let wins=0,losses=0,pending=0,picked=0;const revealed={};for(const g of games){const p=u.picks?.[g.id]||null,win=l.manualResults[g.id]||g.winner;if(p)picked++;if(Date.parse(g.kickoff)<=now)revealed[g.id]=p;if(p&&win)(p===win?wins++:losses++);else if(p&&!win)pending++}rows.push({name,wins,losses,pending,picked,total:games.length,tiebreaker:games.every(g=>Date.parse(g.kickoff)<=now)?u.tiebreakers?.[week]??null:null,picks:revealed})}rows.sort((a,b)=>b.wins-a.wins||a.losses-b.losses||b.picked-a.picked||a.name.localeCompare(b.name));const complete=games.length>0&&games.every(g=>!!(l.manualResults[g.id]||g.winner));const top=complete&&rows.length?Math.max(...rows.map(r=>r.wins)):null;res.json({week,complete,leaders:top===null?[]:rows.filter(r=>r.wins===top).map(r=>r.name),rows})}));
app.get('/api/leagues/:id/admin-summary',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.query.pin))return res.status(403).json({error:'Wrong commissioner PIN'});const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();res.json({pool:l.name,players:Object.entries(l.users).map(([name,u])=>({name,picked:games.filter(g=>u.picks?.[g.id]).length,total:games.length,complete:games.length>0&&games.every(g=>u.picks?.[g.id]),joinedAt:u.joinedAt})),games:games.map(g=>({id:g.id,away:g.away,home:g.home,kickoff:g.kickoff,locked:Date.parse(g.kickoff)<=now,winner:l.manualResults[g.id]||g.winner}))})}));

// Survivor pool: one team per week, no team reuse. A loss or tie eliminates the player.
app.get('/api/leagues/:id/survivor',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),viewer=String(req.query.name||''),ok=auth(l,viewer,req.query.token),now=Date.now();const weeks=await Promise.all(Array.from({length:week},(_,i)=>schedule(i+1)));const players=[];for(const [name,u] of Object.entries(l.users)){u.survivorPicks=u.survivorPicks||{};let alive=true,eliminatedWeek=null;const used=[];for(let wi=0;wi<week;wi++){const pick=u.survivorPicks[wi+1];if(pick)used.push(pick);if(!pick)continue;const g=weeks[wi].find(x=>[x.away,x.home].includes(pick));if(!g)continue;const win=l.manualResults[g.id]||g.winner;if(win&&pick!==win){alive=false;eliminatedWeek=wi+1;break}if(g.status&&String(g.status).toLowerCase().includes('tie')){alive=false;eliminatedWeek=wi+1;break}}const current=u.survivorPicks[week]||null;const currentGame=games.find(g=>[g.away,g.home].includes(current));const reveal=(name===viewer&&ok)||(currentGame&&Date.parse(currentGame.kickoff)<=now);players.push({name,alive,eliminatedWeek,used,currentPick:reveal?current:null,hasPick:!!current})}players.sort((a,b)=>Number(b.alive)-Number(a.alive)||a.name.localeCompare(b.name));res.json({week,games:games.map(g=>({...g,winner:l.manualResults[g.id]||g.winner,locked:Date.parse(g.kickoff)<=now})),players,viewer:ok?viewer:null,rules:'Pick one team each week. You cannot reuse a team. A loss or tie eliminates you.'})}));
app.post('/api/leagues/:id/survivor',route(async(req,res)=>{const l=await getLeague(req.params.id),name=String(req.body.name||'');if(!l)return res.sendStatus(404);if(!auth(l,name,req.body.token))return res.status(403).json({error:'Please sign in again.'});const week=Math.max(1,Math.min(18,+req.body.week||3)),pick=String(req.body.pick||'').toUpperCase(),games=await schedule(week),g=games.find(x=>[x.away,x.home].includes(pick));if(!g)return res.status(400).json({error:'Choose a team playing this week.'});if(Date.parse(g.kickoff)<=Date.now())return res.status(400).json({error:'That team’s game has already kicked off.'});const u=l.users[name];u.survivorPicks=u.survivorPicks||{};const used=Object.entries(u.survivorPicks).filter(([w])=>+w!==week).map(([,t])=>t);if(used.includes(pick))return res.status(400).json({error:'You already used that team in Survivor.'});u.survivorPicks[week]=pick;await putLeague(req.params.id,l);res.json({ok:true,pick})}));


// V7 all-pools preview: local-friendly storage for additional game modes.
const DEFAULT_MODES={pickem:true,survivor:true,confidence:true,ats:true,lock:true,squares:true,doubleSurvivor:true,upset:true,playoffs:true,superBowl:true};
function extrasFor(l){l.poolModes={...DEFAULT_MODES,...(l.poolModes||{})};l.extraPools=l.extraPools||{};return l.extraPools}
app.get('/api/leagues/:id/extras',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);extrasFor(l);const name=String(req.query.name||''),ok=auth(l,name,req.query.token);res.json({modes:l.poolModes,data:ok?(l.extraPools[name]||{}):{},players:Object.keys(l.users)})}));
app.post('/api/leagues/:id/extras',route(async(req,res)=>{const l=await getLeague(req.params.id),name=String(req.body.name||'');if(!l)return res.sendStatus(404);if(!auth(l,name,req.body.token))return res.status(403).json({error:'Please sign in again.'});extrasFor(l);l.extraPools[name]=l.extraPools[name]||{};const mode=String(req.body.mode||'');const allowed=['confidence','ats','lock','squares','doubleSurvivor','upset','playoffs','superBowl'];if(!allowed.includes(mode))return res.status(400).json({error:'Unknown pool mode'});l.extraPools[name][mode]=req.body.value||{};await putLeague(req.params.id,l);res.json({ok:true})}));
app.post('/api/leagues/:id/modes',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});extrasFor(l);for(const k of Object.keys(DEFAULT_MODES))if(k in (req.body.modes||{}))l.poolModes[k]=!!req.body.modes[k];await putLeague(req.params.id,l);res.json({ok:true,modes:l.poolModes})}));

// Live Game Center: refreshed scoreboard plus pool-wide live pick projections.
app.get('/api/leagues/:id/live',route(async(req,res)=>{
  const l=await getLeague(req.params.id); if(!l)return res.sendStatus(404);
  const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();
  const rows=[];
  for(const [name,u] of Object.entries(l.users)){
    let correct=0,wrong=0,leading=0,pending=0;
    for(const g of games){
      const pick=u.picks?.[g.id]; if(!pick)continue;
      const win=l.manualResults[g.id]||g.winner;
      if(win){pick===win?correct++:wrong++;continue}
      const as=Number(g.awayScore),hs=Number(g.homeScore);
      if(Number.isFinite(as)&&Number.isFinite(hs)&&as!==hs){const leader=as>hs?g.away:g.home;pick===leader?leading++:pending++}else pending++;
    }
    rows.push({name,correct,wrong,leading,pending,projected:correct+leading});
  }
  rows.sort((a,b)=>b.projected-a.projected||b.correct-a.correct||a.wrong-b.wrong||a.name.localeCompare(b.name));
  res.json({week,updatedAt:new Date().toISOString(),refreshSeconds:15,games:games.map(g=>({...g,winner:l.manualResults[g.id]||g.winner,locked:Date.parse(g.kickoff)<=now})),standings:rows});
}));

app.get('/health',route(async(req,res)=>{if(pg)await pg.query('SELECT 1');res.json({ok:true,version:'7.3.0-accounts',storage:pg?'postgresql':'local-json'})}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error. Please try again.'})});
const PORT=process.env.PORT||3000;initDB().then(()=>app.listen(PORT,()=>console.log(`Fourth & Pick V7.3 running on port ${PORT} (${pg?'PostgreSQL':'local JSON'} storage)`))).catch(e=>{console.error('Database startup failed:',e);process.exit(1)});
