const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {Pool}=require('pg');
const ExcelJS=require('exceljs');
const app=express();
app.set('trust proxy',1);
app.use(express.json({limit:'1mb'}));
const PUBLIC_DIR=path.join(__dirname,'public');
app.use(express.static(PUBLIC_DIR));
// Explicit root route for hosted deployments (Render, Railway, etc.).
app.get('/',(req,res)=>res.sendFile(path.join(PUBLIC_DIR,'index.html')));

// V6 storage: PostgreSQL when DATABASE_URL is set; safe local JSON fallback for desktop testing.
const LOCAL_DB=path.join(__dirname,'data.json');
let local={leagues:{}}; try{local=JSON.parse(fs.readFileSync(LOCAL_DB,'utf8'))}catch{}
const pg=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false}}):null;
async function initDB(){if(pg)await pg.query(`CREATE TABLE IF NOT EXISTS leagues (id TEXT PRIMARY KEY, data JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`)}
async function getLeague(id){if(!pg)return local.leagues[id]||null;const r=await pg.query('SELECT data FROM leagues WHERE id=$1',[id]);return r.rows[0]?.data||null}
async function putLeague(id,l){if(!pg){local.leagues[id]=l;fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2));return}await pg.query(`INSERT INTO leagues(id,data,updated_at) VALUES($1,$2::jsonb,NOW()) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW()`,[id,JSON.stringify(l)])}

const sha=s=>crypto.createHash('sha256').update(String(s||'')).digest('hex');
const token=()=>crypto.randomBytes(24).toString('hex');
const fallbackW3=[['ATL','GB','2026-09-24T20:15:00-04:00'],['LAC','BUF','2026-09-27T13:00:00-04:00'],['CAR','CLE','2026-09-27T13:00:00-04:00'],['NYJ','DET','2026-09-27T13:00:00-04:00'],['HOU','IND','2026-09-27T13:00:00-04:00'],['NE','JAX','2026-09-27T13:00:00-04:00'],['KC','MIA','2026-09-27T13:00:00-04:00'],['TEN','NYG','2026-09-27T13:00:00-04:00'],['CIN','PIT','2026-09-27T13:00:00-04:00'],['SEA','WAS','2026-09-27T13:00:00-04:00'],['ARI','SF','2026-09-27T16:05:00-04:00'],['MIN','TB','2026-09-27T16:05:00-04:00'],['LV','NO','2026-09-27T16:25:00-04:00'],['BAL','DAL','2026-09-27T16:25:00-04:00'],['LAR','DEN','2026-09-27T20:20:00-04:00'],['PHI','CHI','2026-09-28T20:15:00-04:00']].map((x,i)=>({id:'2026-w3-'+i,away:x[0],home:x[1],kickoff:x[2],status:'scheduled',winner:null,awayScore:null,homeScore:null}));
const cache={}; async function schedule(week){if(cache[week]&&Date.now()-cache[week].at<60000)return cache[week].games;try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?dates=2026&seasontype=2&week=${week}`,{signal:AbortSignal.timeout(5000)});if(!r.ok)throw 0;const j=await r.json();const games=j.events.map(e=>{const c=e.competitions[0],a=c.competitors.find(x=>x.homeAway==='away'),h=c.competitors.find(x=>x.homeAway==='home');let winner=null;if(c.status.type.completed)winner=(+a.score>+h.score)?a.team.abbreviation:h.team.abbreviation;return{id:e.id,away:a.team.abbreviation,home:h.team.abbreviation,kickoff:e.date,status:c.status.type.name,winner,awayScore:a.score,homeScore:h.score}});cache[week]={at:Date.now(),games};return games}catch(e){return week===3?fallbackW3:[]}}
const adminOK=(l,p)=>sha(p)===l.adminHash; const auth=(l,name,t)=>l?.users?.[name]&&l.users[name].tokenHash===sha(t);
const route=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);

app.post('/api/leagues',route(async(req,res)=>{const id=crypto.randomBytes(4).toString('hex'),pin=String(req.body.pin||'').trim(),owner=String(req.body.owner||'').trim().slice(0,40),playerPin=String(req.body.playerPin||'').trim();if(pin.length<4||!owner||playerPin.length<4)return res.status(400).json({error:'Pool name, your name, commissioner PIN and player PIN (4+ chars) are required.'});const l={name:String(req.body.name||'Fourth & Pick').trim().slice(0,60),season:2026,adminHash:sha(pin),users:{},manualResults:{},createdAt:new Date().toISOString()};const t=token();l.users[owner]={pinHash:sha(playerPin),tokenHash:sha(t),picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};await putLeague(id,l);res.json({id,name:owner,token:t})}));
app.post('/api/leagues/:id/auth',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.status(404).json({error:'Pool not found'});const name=String(req.body.name||'').trim().slice(0,40),pin=String(req.body.pin||'').trim();if(!name||pin.length<4)return res.status(400).json({error:'Name and 4+ character player PIN required.'});let u=l.users[name];if(u&&u.pinHash&&u.pinHash!==sha(pin))return res.status(403).json({error:'That name is already registered with a different PIN.'});const t=token();if(!u)u=l.users[name]={picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};u.pinHash=sha(pin);u.tokenHash=sha(t);await putLeague(req.params.id,l);res.json({name,token:t})}));
app.get('/api/leagues/:id',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.status(404).json({error:'Pool not found'});const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();const viewer=String(req.query.name||''),ok=auth(l,viewer,req.query.token);const users={};for(const [n,u] of Object.entries(l.users)){const picks={};for(const g of games){const locked=Date.parse(g.kickoff)<=now;if((n===viewer&&ok)||locked)picks[g.id]=u.picks?.[g.id]||null}users[n]={picks,tiebreaker:(n===viewer&&ok||games.every(g=>Date.parse(g.kickoff)<=now))?u.tiebreakers?.[week]??null:null}}res.json({id:req.params.id,name:l.name,season:l.season,week,games:games.map(g=>({...g,winner:l.manualResults[g.id]||g.winner,locked:Date.parse(g.kickoff)<=now})),users,viewer:ok?viewer:null})}));
app.post('/api/leagues/:id/picks',route(async(req,res)=>{const l=await getLeague(req.params.id),name=String(req.body.name||'');if(!l)return res.sendStatus(404);if(!auth(l,name,req.body.token))return res.status(403).json({error:'Please sign in again.'});const week=Math.max(1,Math.min(18,+req.body.week||3)),games=await schedule(week),byId=Object.fromEntries(games.map(g=>[g.id,g])),now=Date.now();for(const [gid,pick] of Object.entries(req.body.picks||{})){const g=byId[gid];if(g&&Date.parse(g.kickoff)>now&&[g.away,g.home].includes(pick))l.users[name].picks[gid]=pick}if(games.some(g=>Date.parse(g.kickoff)>now))l.users[name].tiebreakers[week]=Math.max(0,Math.min(150,+req.body.tiebreaker||0));await putLeague(req.params.id,l);res.json({ok:true})}));
app.post('/api/leagues/:id/results',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});for(const [gid,w] of Object.entries(req.body.results||{})){if(w)l.manualResults[gid]=w;else delete l.manualResults[gid]}await putLeague(req.params.id,l);res.json({ok:true})}));
app.get('/api/leagues/:id/standings',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const weeks=await Promise.all(Array.from({length:18},(_,i)=>schedule(i+1))),rows=[];for(const [name,u] of Object.entries(l.users)){let wins=0,losses=0,pending=0;const weekly={};for(let wi=0;wi<18;wi++){let w=0,lo=0;for(const g of weeks[wi]){const win=l.manualResults[g.id]||g.winner,p=u.picks?.[g.id];if(!p)continue;if(!win){pending++;continue}p===win?w++:lo++}weekly[wi+1]={wins:w,losses:lo};wins+=w;losses+=lo}rows.push({name,wins,losses,pending,pct:wins+losses?wins/(wins+losses):0,weekly})}rows.sort((a,b)=>b.wins-a.wins||a.losses-b.losses||a.name.localeCompare(b.name));res.json(rows)}));
async function exportData(l){const weeks=await Promise.all(Array.from({length:18},(_,i)=>schedule(i+1))),games=weeks.flat(),rows=[];for(const [name,u] of Object.entries(l.users)){let w=0,lo=0;for(const g of games){const win=l.manualResults[g.id]||g.winner,p=u.picks?.[g.id];if(win&&p)(p===win?w++:lo++)}rows.push({name,w,lo,pct:w+lo?100*w/(w+lo):0,picks:games.map(g=>u.picks?.[g.id]||'')})}return {games,rows}}
app.get('/api/leagues/:id/export.csv',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const {games,rows}=await exportData(l);const out=[['Player','Wins','Losses','Win %',...games.map(g=>`${g.away}@${g.home}`)],...rows.map(r=>[r.name,r.w,r.lo,r.w+r.lo?r.pct.toFixed(1)+'%':'',...r.picks])];res.setHeader('Content-Disposition',`attachment; filename="${l.name.replace(/[^a-z0-9]/gi,'_')}_2026.csv"`);res.type('text/csv').send(out.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'))}));
app.get('/api/leagues/:id/export.xlsx',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const {games,rows}=await exportData(l),wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Season Picks');ws.addRow(['Player','Wins','Losses','Win %',...games.map(g=>`${g.away}@${g.home}`)]);for(const r of rows)ws.addRow([r.name,r.w,r.lo,r.w+r.lo?r.pct/100:null,...r.picks]);ws.getRow(1).font={bold:true};ws.views=[{state:'frozen',xSplit:1,ySplit:1}];ws.columns.forEach(c=>c.width=Math.min(24,Math.max(10,...c.values.slice(1).map(v=>String(v??'').length+2))));ws.getColumn(4).numFmt='0.0%';const summary=wb.addWorksheet('Leaderboard');summary.addRow(['Player','Wins','Losses','Win %']);rows.sort((a,b)=>b.w-a.w||a.lo-b.lo||a.name.localeCompare(b.name)).forEach(r=>summary.addRow([r.name,r.w,r.lo,r.w+r.lo?r.pct/100:null]));summary.getRow(1).font={bold:true};summary.getColumn(4).numFmt='0.0%';summary.columns.forEach(c=>c.width=18);res.setHeader('Content-Disposition',`attachment; filename="${l.name.replace(/[^a-z0-9]/gi,'_')}_2026.xlsx"`);res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');await wb.xlsx.write(res);res.end()}));
app.get('/api/leagues/:id/week-summary',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();const rows=[];for(const [name,u] of Object.entries(l.users)){let wins=0,losses=0,pending=0,picked=0;const revealed={};for(const g of games){const p=u.picks?.[g.id]||null,win=l.manualResults[g.id]||g.winner;if(p)picked++;if(Date.parse(g.kickoff)<=now)revealed[g.id]=p;if(p&&win)(p===win?wins++:losses++);else if(p&&!win)pending++}rows.push({name,wins,losses,pending,picked,total:games.length,tiebreaker:games.every(g=>Date.parse(g.kickoff)<=now)?u.tiebreakers?.[week]??null:null,picks:revealed})}rows.sort((a,b)=>b.wins-a.wins||a.losses-b.losses||b.picked-a.picked||a.name.localeCompare(b.name));const complete=games.length>0&&games.every(g=>!!(l.manualResults[g.id]||g.winner));const top=complete&&rows.length?Math.max(...rows.map(r=>r.wins)):null;res.json({week,complete,leaders:top===null?[]:rows.filter(r=>r.wins===top).map(r=>r.name),rows})}));
app.get('/api/leagues/:id/admin-summary',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.query.pin))return res.status(403).json({error:'Wrong commissioner PIN'});const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();res.json({pool:l.name,players:Object.entries(l.users).map(([name,u])=>({name,picked:games.filter(g=>u.picks?.[g.id]).length,total:games.length,complete:games.length>0&&games.every(g=>u.picks?.[g.id]),joinedAt:u.joinedAt})),games:games.map(g=>({id:g.id,away:g.away,home:g.home,kickoff:g.kickoff,locked:Date.parse(g.kickoff)<=now,winner:l.manualResults[g.id]||g.winner}))})}));
app.get('/health',route(async(req,res)=>{if(pg)await pg.query('SELECT 1');res.json({ok:true,version:'6.1.0',storage:pg?'postgresql':'local-json'})}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error. Please try again.'})});
const PORT=process.env.PORT||3000;initDB().then(()=>app.listen(PORT,()=>console.log(`Fourth & Pick V6.1 running on port ${PORT} (${pg?'PostgreSQL':'local JSON'} storage)`))).catch(e=>{console.error('Database startup failed:',e);process.exit(1)});
