const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {Pool}=require('pg');
const ExcelJS=require('exceljs');
const app=express();
app.set('trust proxy',1);
app.use(express.json({limit:'1mb'}));
const PUBLIC_DIR=path.join(__dirname,'public');
app.use(express.static(PUBLIC_DIR));
// Explicit root route for hosted deployments (Render, Railway, etc.).
app.get('/',(req,res)=>res.sendFile(path.join(PUBLIC_DIR,'index.html')));

// V6 storage: PostgreSQL when DATABASE_URL is set; safe local JSON fallback for desktop testing.
const LOCAL_DB=path.join(__dirname,'data.json');
let local={leagues:{}}; try{local=JSON.parse(fs.readFileSync(LOCAL_DB,'utf8'))}catch{}
const pg=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false}}):null;
async function initDB(){if(pg){
  await pg.query(`CREATE TABLE IF NOT EXISTS leagues (id TEXT PRIMARY KEY, data JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await pg.query(`CREATE TABLE IF NOT EXISTS accounts (username TEXT PRIMARY KEY, display_name TEXT NOT NULL, salt TEXT NOT NULL, password_hash TEXT NOT NULL, session_hash TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await pg.query(`CREATE TABLE IF NOT EXISTS memberships (account_id TEXT NOT NULL REFERENCES accounts(username) ON DELETE CASCADE, league_id TEXT NOT NULL, player_name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'player', joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(account_id,league_id))`);
  await pg.query(`ALTER TABLE accounts ADD COLUMN IF NOT EXISTS email TEXT`);
  await pg.query(`ALTER TABLE accounts ADD COLUMN IF NOT EXISTS email_reminders BOOLEAN NOT NULL DEFAULT TRUE`);
}else{local.accounts=local.accounts||{};local.memberships=local.memberships||[];local.emailOutbox=local.emailOutbox||[]}}
async function getLeague(id){if(!pg)return local.leagues[id]||null;const r=await pg.query('SELECT data FROM leagues WHERE id=$1',[id]);return r.rows[0]?.data||null}
async function putLeague(id,l){if(!pg){local.leagues[id]=l;fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2));return}await pg.query(`INSERT INTO leagues(id,data,updated_at) VALUES($1,$2::jsonb,NOW()) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW()`,[id,JSON.stringify(l)])}

const sha=s=>crypto.createHash('sha256').update(String(s||'')).digest('hex');
const token=()=>crypto.randomBytes(24).toString('hex');
const fallbackW3=[['ATL','GB','2026-09-24T20:15:00-04:00'],['LAC','BUF','2026-09-27T13:00:00-04:00'],['CAR','CLE','2026-09-27T13:00:00-04:00'],['NYJ','DET','2026-09-27T13:00:00-04:00'],['HOU','IND','2026-09-27T13:00:00-04:00'],['NE','JAX','2026-09-27T13:00:00-04:00'],['KC','MIA','2026-09-27T13:00:00-04:00'],['TEN','NYG','2026-09-27T13:00:00-04:00'],['CIN','PIT','2026-09-27T13:00:00-04:00'],['SEA','WAS','2026-09-27T13:00:00-04:00'],['ARI','SF','2026-09-27T16:05:00-04:00'],['MIN','TB','2026-09-27T16:05:00-04:00'],['LV','NO','2026-09-27T16:25:00-04:00'],['BAL','DAL','2026-09-27T16:25:00-04:00'],['LAR','DEN','2026-09-27T20:20:00-04:00'],['PHI','CHI','2026-09-28T20:15:00-04:00']].map((x,i)=>({id:'2026-w3-'+i,away:x[0],home:x[1],kickoff:x[2],status:'scheduled',winner:null,awayScore:null,homeScore:null}));
const cache={}; async function schedule(week){if(cache[week]&&Date.now()-cache[week].at<15000)return cache[week].games;try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?dates=2026&seasontype=2&week=${week}`,{signal:AbortSignal.timeout(5000)});if(!r.ok)throw 0;const j=await r.json();const games=j.events.map(e=>{const c=e.competitions[0],a=c.competitors.find(x=>x.homeAway==='away'),h=c.competitors.find(x=>x.homeAway==='home');let winner=null;if(c.status.type.completed)winner=(+a.score>+h.score)?a.team.abbreviation:h.team.abbreviation;return{id:e.id,away:a.team.abbreviation,home:h.team.abbreviation,kickoff:e.date,status:c.status.type.name,statusDetail:c.status.type.detail||c.status.type.shortDetail||'',clock:c.status.displayClock||'',period:c.status.period||0,winner,awayScore:a.score,homeScore:h.score}});cache[week]={at:Date.now(),games};return games}catch(e){return week===3?fallbackW3:[]}}
const adminOK=(l,p)=>sha(p)===l.adminHash; const auth=(l,name,t)=>l?.users?.[name]&&l.users[name].tokenHash===sha(t);
const route=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const uname=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9_.-]/g,'').slice(0,32);
const passHash=(password,salt)=>crypto.scryptSync(String(password),salt,64).toString('hex');
async function getAccount(username){username=uname(username);if(!pg)return local.accounts?.[username]||null;const r=await pg.query('SELECT * FROM accounts WHERE username=$1',[username]);return r.rows[0]||null}
async function saveAccount(a){if(!pg){local.accounts=local.accounts||{};local.accounts[a.username]=a;fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2));return}await pg.query(`INSERT INTO accounts(username,display_name,salt,password_hash,session_hash,email,email_reminders) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(username) DO UPDATE SET display_name=EXCLUDED.display_name,salt=EXCLUDED.salt,password_hash=EXCLUDED.password_hash,session_hash=EXCLUDED.session_hash,email=COALESCE(EXCLUDED.email,accounts.email),email_reminders=COALESCE(EXCLUDED.email_reminders,accounts.email_reminders)`,[a.username,a.display_name,a.salt,a.password_hash,a.session_hash,a.email||null,a.email_reminders!==false])}
async function accountByToken(t){if(!t)return null;const h=sha(t);if(!pg){return Object.values(local.accounts||{}).find(a=>a.session_hash===h)||null}const r=await pg.query('SELECT * FROM accounts WHERE session_hash=$1',[h]);return r.rows[0]||null}
async function addMembership(accountId,leagueId,playerName,role='player'){if(!pg){local.memberships=local.memberships||[];let m=local.memberships.find(x=>x.account_id===accountId&&x.league_id===leagueId);if(m){m.player_name=playerName;m.role=role==='commissioner'?'commissioner':m.role}else local.memberships.push({account_id:accountId,league_id:leagueId,player_name:playerName,role,joined_at:new Date().toISOString()});fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2));return}await pg.query(`INSERT INTO memberships(account_id,league_id,player_name,role) VALUES($1,$2,$3,$4) ON CONFLICT(account_id,league_id) DO UPDATE SET player_name=EXCLUDED.player_name,role=CASE WHEN memberships.role='commissioner' THEN 'commissioner' ELSE EXCLUDED.role END`,[accountId,leagueId,playerName,role])}
async function getMemberships(accountId){if(!pg)return (local.memberships||[]).filter(x=>x.account_id===accountId);const r=await pg.query('SELECT * FROM memberships WHERE account_id=$1 ORDER BY joined_at DESC',[accountId]);return r.rows}

// V7.3 global account + My Pools API. Existing pool data stays untouched.
app.post('/api/account/register',route(async(req,res)=>{const username=uname(req.body.username),display=String(req.body.displayName||'').trim().slice(0,40),password=String(req.body.password||''),email=String(req.body.email||'').trim().toLowerCase().slice(0,160);if(username.length<3||!display||password.length<6)return res.status(400).json({error:'Username must be 3+ characters, display name is required, and password must be 6+ characters.'});if(await getAccount(username))return res.status(409).json({error:'That username is already taken.'});const salt=crypto.randomBytes(16).toString('hex'),t=token(),a={username,display_name:display,salt,password_hash:passHash(password,salt),session_hash:sha(t),email,email_reminders:true,created_at:new Date().toISOString()};await saveAccount(a);res.json({username,displayName:display,token:t})}));
app.post('/api/account/login',route(async(req,res)=>{const username=uname(req.body.username),password=String(req.body.password||''),a=await getAccount(username);if(!a||!crypto.timingSafeEqual(Buffer.from(a.password_hash,'hex'),Buffer.from(passHash(password,a.salt),'hex')))return res.status(403).json({error:'Incorrect username or password.'});const t=token();a.session_hash=sha(t);await saveAccount(a);res.json({username:a.username,displayName:a.display_name,token:t})}));
app.get('/api/account/me',route(async(req,res)=>{const a=await accountByToken(req.query.token);if(!a)return res.status(401).json({error:'Please sign in.'});const ms=await getMemberships(a.username),pools=[];for(const m of ms){const l=await getLeague(m.league_id);if(l)pools.push({id:m.league_id,name:l.name,playerName:m.player_name,role:m.role,season:l.season||2026,modes:{...DEFAULT_MODES,...(l.poolModes||{})}})}res.json({username:a.username,displayName:a.display_name,email:a.email||'',emailReminders:a.email_reminders!==false,pools})}));
app.post('/api/account/pools/:id/join',route(async(req,res)=>{const a=await accountByToken(req.body.accountToken),l=await getLeague(req.params.id);if(!a)return res.status(401).json({error:'Please sign in to your Fourth & Pick account.'});if(!l)return res.status(404).json({error:'Pool not found.'});const requestedLegacy=String(req.body.legacyName||'').trim().slice(0,40),browserName=String(req.body.browserName||'').trim().slice(0,40),browserToken=String(req.body.legacyToken||''),pp=String(req.body.playerPin||'');let name=requestedLegacy||a.display_name;let u=l.users[name];const browserOK=browserName===name&&auth(l,name,browserToken);if(requestedLegacy){if(!u)return res.status(404).json({error:'That player name was not found in this pool. Enter the exact name used in the old pool.'});if(!browserOK&&(!pp||!u.pinHash||u.pinHash!==sha(pp)))return res.status(403).json({error:'Old player name or pool PIN is incorrect.'});}else if(u&&u.pinHash&&!browserOK){if(!pp||u.pinHash!==sha(pp))return res.status(409).json({error:'EXISTING_PLAYER_VERIFICATION_REQUIRED'});}const t=token();if(!u)u=l.users[name]={picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};u.tokenHash=sha(t);await putLeague(req.params.id,l);await addMembership(a.username,req.params.id,name,'player');res.json({id:req.params.id,name,token:t,linkedExisting:!!requestedLegacy||browserOK})}));
app.post('/api/account/pools/:id/open',route(async(req,res)=>{const a=await accountByToken(req.body.accountToken);if(!a)return res.status(401).json({error:'Please sign in.'});const ms=await getMemberships(a.username),m=ms.find(x=>x.league_id===req.params.id);if(!m)return res.status(403).json({error:'You are not a member of this pool.'});const l=await getLeague(req.params.id);if(!l)return res.status(404).json({error:'Pool not found.'});const t=token();if(!l.users[m.player_name])return res.status(409).json({error:'Your pool membership needs to be rejoined.'});l.users[m.player_name].tokenHash=sha(t);await putLeague(req.params.id,l);res.json({id:req.params.id,name:m.player_name,token:t,role:m.role})}));


// V8.3.5 Pool Discovery & Membership Management.
async function removeMembership(accountId,leagueId){if(!pg){local.memberships=(local.memberships||[]).filter(x=>!(x.account_id===accountId&&x.league_id===leagueId));fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2));return}await pg.query('DELETE FROM memberships WHERE account_id=$1 AND league_id=$2',[accountId,leagueId])}
async function allLeagues(){if(!pg)return Object.entries(local.leagues||{}).map(([id,data])=>({id,data}));const r=await pg.query('SELECT id,data FROM leagues ORDER BY updated_at DESC');return r.rows}
app.get('/api/account/pools/search',route(async(req,res)=>{const a=await accountByToken(req.query.token);if(!a)return res.status(401).json({error:'Please sign in.'});const q=String(req.query.q||'').trim().toLowerCase();if(q.length<2)return res.json({results:[]});const ms=await getMemberships(a.username),joined=new Set(ms.map(x=>x.league_id)),rows=[];for(const x of await allLeagues()){const l=x.data||{},privacy=l.poolPrivacy||'invite',code=String(l.poolCode||x.id).toLowerCase(),name=String(l.name||'');const exactCode=code===q||String(x.id).toLowerCase()===q;if(privacy==='invite'&&!exactCode)continue;if(!exactCode&&!name.toLowerCase().includes(q))continue;rows.push({id:x.id,name,code:l.poolCode||x.id,privacy,approvalRequired:privacy==='searchable',members:Object.keys(l.users||{}).length,joined:joined.has(x.id)});if(rows.length>=20)break}res.json({results:rows})}));
app.post('/api/account/pools/:id/discovery-join',route(async(req,res)=>{const a=await accountByToken(req.body.accountToken),l=await getLeague(req.params.id);if(!a)return res.status(401).json({error:'Please sign in.'});if(!l)return res.status(404).json({error:'Pool not found.'});const ms=await getMemberships(a.username);if(ms.some(x=>x.league_id===req.params.id))return res.json({ok:true,alreadyJoined:true});const privacy=l.poolPrivacy||'invite';if(privacy==='searchable'){l.joinRequests=l.joinRequests||[];if(!l.joinRequests.some(x=>x.accountId===a.username&&x.status==='pending'))l.joinRequests.push({id:crypto.randomBytes(5).toString('hex'),accountId:a.username,displayName:a.display_name,requestedAt:new Date().toISOString(),status:'pending'});await putLeague(req.params.id,l);return res.json({ok:true,pending:true})}const name=a.display_name;let u=l.users[name];if(u&&u.linkedAccount&&u.linkedAccount!==a.username)return res.status(409).json({error:'That player name is already in use in this pool.'});if(!u)u=l.users[name]={picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};u.linkedAccount=a.username;await putLeague(req.params.id,l);await addMembership(a.username,req.params.id,name,'player');res.json({ok:true,joined:true})}));
app.post('/api/account/pools/:id/leave',route(async(req,res)=>{const a=await accountByToken(req.body.accountToken);if(!a)return res.status(401).json({error:'Please sign in.'});const ms=await getMemberships(a.username),m=ms.find(x=>x.league_id===req.params.id);if(!m)return res.status(404).json({error:'You are not a member of this pool.'});if(m.role==='commissioner'){const all=await membershipsForLeague(req.params.id);if(!all.some(x=>x.role==='commissioner'&&x.account_id!==a.username))return res.status(409).json({error:'Transfer commissioner control before leaving this pool.'})}await removeMembership(a.username,req.params.id);const l=await getLeague(req.params.id);if(l?.users?.[m.player_name]){l.users[m.player_name].inactive=true;l.users[m.player_name].leftAt=new Date().toISOString();await putLeague(req.params.id,l)}res.json({ok:true})}));
app.get('/api/leagues/:id/membership-admin',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.query.pin))return res.status(403).json({error:'Wrong commissioner PIN'});const members=await membershipsForLeague(req.params.id);res.json({privacy:l.poolPrivacy||'invite',code:l.poolCode||req.params.id,requests:(l.joinRequests||[]).filter(x=>x.status==='pending'),members:members.map(x=>({accountId:x.account_id,playerName:x.player_name,role:x.role}))})}));
app.post('/api/leagues/:id/membership-admin',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});if(['public','searchable','invite'].includes(req.body.privacy))l.poolPrivacy=req.body.privacy;if(req.body.action==='approve'){const r=(l.joinRequests||[]).find(x=>x.id===req.body.requestId&&x.status==='pending');if(!r)return res.status(404).json({error:'Join request not found.'});const a=await getAccount(r.accountId);if(!a)return res.status(404).json({error:'Account no longer exists.'});let name=a.display_name;if(l.users[name]?.linkedAccount&&l.users[name].linkedAccount!==a.username)name=`${name} (${a.username})`.slice(0,40);l.users[name]=l.users[name]||{picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};l.users[name].linkedAccount=a.username;l.users[name].inactive=false;await addMembership(a.username,req.params.id,name,'player');r.status='approved';r.decidedAt=new Date().toISOString()}if(req.body.action==='deny'){const r=(l.joinRequests||[]).find(x=>x.id===req.body.requestId);if(r){r.status='denied';r.decidedAt=new Date().toISOString()}}if(req.body.action==='transfer'){const target=String(req.body.accountId||'');const members=await membershipsForLeague(req.params.id),m=members.find(x=>x.account_id===target);if(!m)return res.status(404).json({error:'Target member not found.'});if(pg){await pg.query("UPDATE memberships SET role='player' WHERE league_id=$1 AND role='commissioner'",[req.params.id]);await pg.query("UPDATE memberships SET role='commissioner' WHERE league_id=$1 AND account_id=$2",[req.params.id,target])}else{for(const x of local.memberships||[])if(x.league_id===req.params.id)x.role=x.account_id===target?'commissioner':'player';fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2))}}await putLeague(req.params.id,l);res.json({ok:true})}));
app.post('/api/leagues',route(async(req,res)=>{const id=crypto.randomBytes(4).toString('hex'),pin=String(req.body.pin||'').trim(),owner=String(req.body.owner||'').trim().slice(0,40),playerPin=String(req.body.playerPin||'').trim();if(pin.length<4||!owner||playerPin.length<4)return res.status(400).json({error:'Pool name, your name, commissioner PIN and player PIN (4+ chars) are required.'});const l={name:String(req.body.name||'Fourth & Pick').trim().slice(0,60),season:2026,adminHash:sha(pin),users:{},manualResults:{},poolPrivacy:'invite',poolCode:id.toUpperCase(),joinRequests:[],createdAt:new Date().toISOString()};const t=token();l.users[owner]={pinHash:sha(playerPin),tokenHash:sha(t),picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};await putLeague(id,l);const acct=await accountByToken(req.body.accountToken);if(acct)await addMembership(acct.username,id,owner,'commissioner');res.json({id,name:owner,token:t})}));
app.post('/api/leagues/:id/auth',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.status(404).json({error:'Pool not found'});const name=String(req.body.name||'').trim().slice(0,40),pin=String(req.body.pin||'').trim();if(!name||pin.length<4)return res.status(400).json({error:'Name and 4+ character player PIN required.'});let u=l.users[name];if(u&&u.pinHash&&u.pinHash!==sha(pin))return res.status(403).json({error:'That name is already registered with a different PIN.'});const t=token();if(!u)u=l.users[name]={picks:{},tiebreakers:{},joinedAt:new Date().toISOString()};u.pinHash=sha(pin);u.tokenHash=sha(t);await putLeague(req.params.id,l);res.json({name,token:t})}));
app.get('/api/leagues/:id',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.status(404).json({error:'Pool not found'});const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();const viewer=String(req.query.name||''),ok=auth(l,viewer,req.query.token);const users={};for(const [n,u] of Object.entries(l.users)){const picks={};for(const g of games){const locked=Date.parse(g.kickoff)<=now;if((n===viewer&&ok)||locked)picks[g.id]=u.picks?.[g.id]||null}users[n]={picks,tiebreaker:(n===viewer&&ok||games.every(g=>Date.parse(g.kickoff)<=now))?u.tiebreakers?.[week]??null:null}}res.json({id:req.params.id,name:l.name,season:l.season,week,games:games.map(g=>({...g,winner:l.manualResults[g.id]||g.winner,locked:Date.parse(g.kickoff)<=now})),users,viewer:ok?viewer:null})}));
app.post('/api/leagues/:id/picks',route(async(req,res)=>{const l=await getLeague(req.params.id),name=String(req.body.name||'');if(!l)return res.sendStatus(404);if(!auth(l,name,req.body.token))return res.status(403).json({error:'Please sign in again.'});const week=Math.max(1,Math.min(18,+req.body.week||3)),games=await schedule(week),byId=Object.fromEntries(games.map(g=>[g.id,g])),now=Date.now();for(const [gid,pick] of Object.entries(req.body.picks||{})){const g=byId[gid];if(g&&Date.parse(g.kickoff)>now&&[g.away,g.home].includes(pick))l.users[name].picks[gid]=pick}if(games.some(g=>Date.parse(g.kickoff)>now))l.users[name].tiebreakers[week]=Math.max(0,Math.min(150,+req.body.tiebreaker||0));await putLeague(req.params.id,l);res.json({ok:true})}));
app.post('/api/leagues/:id/results',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});for(const [gid,w] of Object.entries(req.body.results||{})){if(w)l.manualResults[gid]=w;else delete l.manualResults[gid]}await putLeague(req.params.id,l);res.json({ok:true})}));
app.get('/api/leagues/:id/standings',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const weeks=await Promise.all(Array.from({length:18},(_,i)=>schedule(i+1))),rows=[];for(const [name,u] of Object.entries(l.users)){let wins=0,losses=0,pending=0;const weekly={};for(let wi=0;wi<18;wi++){let w=0,lo=0;for(const g of weeks[wi]){const win=l.manualResults[g.id]||g.winner,p=u.picks?.[g.id];if(!p)continue;if(!win){pending++;continue}p===win?w++:lo++}weekly[wi+1]={wins:w,losses:lo};wins+=w;losses+=lo}rows.push({name,wins,losses,pending,pct:wins+losses?wins/(wins+losses):0,weekly})}rows.sort((a,b)=>b.wins-a.wins||a.losses-b.losses||a.name.localeCompare(b.name));res.json(rows)}));
async function exportData(l){const weeks=await Promise.all(Array.from({length:18},(_,i)=>schedule(i+1))),games=weeks.flat(),rows=[];for(const [name,u] of Object.entries(l.users)){let w=0,lo=0;for(const g of games){const win=l.manualResults[g.id]||g.winner,p=u.picks?.[g.id];if(win&&p)(p===win?w++:lo++)}rows.push({name,w,lo,pct:w+lo?100*w/(w+lo):0,picks:games.map(g=>u.picks?.[g.id]||'')})}return {games,rows}}
app.get('/api/leagues/:id/export.csv',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const {games,rows}=await exportData(l);const out=[['Player','Wins','Losses','Win %',...games.map(g=>`${g.away}@${g.home}`)],...rows.map(r=>[r.name,r.w,r.lo,r.w+r.lo?r.pct.toFixed(1)+'%':'',...r.picks])];res.setHeader('Content-Disposition',`attachment; filename="${l.name.replace(/[^a-z0-9]/gi,'_')}_2026.csv"`);res.type('text/csv').send(out.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'))}));
app.get('/api/leagues/:id/export.xlsx',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const {games,rows}=await exportData(l),wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Season Picks');ws.addRow(['Player','Wins','Losses','Win %',...games.map(g=>`${g.away}@${g.home}`)]);for(const r of rows)ws.addRow([r.name,r.w,r.lo,r.w+r.lo?r.pct/100:null,...r.picks]);ws.getRow(1).font={bold:true};ws.views=[{state:'frozen',xSplit:1,ySplit:1}];ws.columns.forEach(c=>c.width=Math.min(24,Math.max(10,...c.values.slice(1).map(v=>String(v??'').length+2))));ws.getColumn(4).numFmt='0.0%';const summary=wb.addWorksheet('Leaderboard');summary.addRow(['Player','Wins','Losses','Win %']);rows.sort((a,b)=>b.w-a.w||a.lo-b.lo||a.name.localeCompare(b.name)).forEach(r=>summary.addRow([r.name,r.w,r.lo,r.w+r.lo?r.pct/100:null]));summary.getRow(1).font={bold:true};summary.getColumn(4).numFmt='0.0%';summary.columns.forEach(c=>c.width=18);res.setHeader('Content-Disposition',`attachment; filename="${l.name.replace(/[^a-z0-9]/gi,'_')}_2026.xlsx"`);res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');await wb.xlsx.write(res);res.end()}));
app.get('/api/leagues/:id/week-summary',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();const rows=[];for(const [name,u] of Object.entries(l.users)){let wins=0,losses=0,pending=0,picked=0;const revealed={};for(const g of games){const p=u.picks?.[g.id]||null,win=l.manualResults[g.id]||g.winner;if(p)picked++;if(Date.parse(g.kickoff)<=now)revealed[g.id]=p;if(p&&win)(p===win?wins++:losses++);else if(p&&!win)pending++}rows.push({name,wins,losses,pending,picked,total:games.length,tiebreaker:games.every(g=>Date.parse(g.kickoff)<=now)?u.tiebreakers?.[week]??null:null,picks:revealed})}rows.sort((a,b)=>b.wins-a.wins||a.losses-b.losses||b.picked-a.picked||a.name.localeCompare(b.name));const complete=games.length>0&&games.every(g=>!!(l.manualResults[g.id]||g.winner));const top=complete&&rows.length?Math.max(...rows.map(r=>r.wins)):null;res.json({week,complete,leaders:top===null?[]:rows.filter(r=>r.wins===top).map(r=>r.name),rows})}));
app.get('/api/leagues/:id/admin-summary',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.query.pin))return res.status(403).json({error:'Wrong commissioner PIN'});const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();res.json({pool:l.name,players:Object.entries(l.users).map(([name,u])=>({name,picked:games.filter(g=>u.picks?.[g.id]).length,total:games.length,complete:games.length>0&&games.every(g=>u.picks?.[g.id]),joinedAt:u.joinedAt})),games:games.map(g=>({id:g.id,away:g.away,home:g.home,kickoff:g.kickoff,locked:Date.parse(g.kickoff)<=now,winner:l.manualResults[g.id]||g.winner}))})}));

// Survivor pool: one team per week, no team reuse. A loss or tie eliminates the player.
app.get('/api/leagues/:id/survivor',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),viewer=String(req.query.name||''),ok=auth(l,viewer,req.query.token),now=Date.now();const weeks=await Promise.all(Array.from({length:week},(_,i)=>schedule(i+1)));const players=[];for(const [name,u] of Object.entries(l.users)){u.survivorPicks=u.survivorPicks||{};let alive=true,eliminatedWeek=null;const used=[];for(let wi=0;wi<week;wi++){const pick=u.survivorPicks[wi+1];if(pick)used.push(pick);if(!pick)continue;const g=weeks[wi].find(x=>[x.away,x.home].includes(pick));if(!g)continue;const win=l.manualResults[g.id]||g.winner;if(win&&pick!==win){alive=false;eliminatedWeek=wi+1;break}if(g.status&&String(g.status).toLowerCase().includes('tie')){alive=false;eliminatedWeek=wi+1;break}}const current=u.survivorPicks[week]||null;const currentGame=games.find(g=>[g.away,g.home].includes(current));const reveal=(name===viewer&&ok)||(currentGame&&Date.parse(currentGame.kickoff)<=now);players.push({name,alive,eliminatedWeek,used,currentPick:reveal?current:null,hasPick:!!current})}players.sort((a,b)=>Number(b.alive)-Number(a.alive)||a.name.localeCompare(b.name));res.json({week,games:games.map(g=>({...g,winner:l.manualResults[g.id]||g.winner,locked:Date.parse(g.kickoff)<=now})),players,viewer:ok?viewer:null,rules:'Pick one team each week. You cannot reuse a team. A loss or tie eliminates you.'})}));
app.post('/api/leagues/:id/survivor',route(async(req,res)=>{const l=await getLeague(req.params.id),name=String(req.body.name||'');if(!l)return res.sendStatus(404);if(!auth(l,name,req.body.token))return res.status(403).json({error:'Please sign in again.'});const week=Math.max(1,Math.min(18,+req.body.week||3)),pick=String(req.body.pick||'').toUpperCase(),games=await schedule(week),g=games.find(x=>[x.away,x.home].includes(pick));if(!g)return res.status(400).json({error:'Choose a team playing this week.'});if(Date.parse(g.kickoff)<=Date.now())return res.status(400).json({error:'That team’s game has already kicked off.'});const u=l.users[name];u.survivorPicks=u.survivorPicks||{};const used=Object.entries(u.survivorPicks).filter(([w])=>+w!==week).map(([,t])=>t);if(used.includes(pick))return res.status(400).json({error:'You already used that team in Survivor.'});u.survivorPicks[week]=pick;await putLeague(req.params.id,l);res.json({ok:true,pick})}));


// V7 all-pools preview: local-friendly storage for additional game modes.
const DEFAULT_MODES={pickem:true,survivor:true,confidence:true,ats:true,lock:true,squares:true,doubleSurvivor:true,upset:true,playoffs:true,superBowl:true};
function extrasFor(l){l.poolModes={...DEFAULT_MODES,...(l.poolModes||{})};l.extraPools=l.extraPools||{};return l.extraPools}
app.get('/api/leagues/:id/extras',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);extrasFor(l);const name=String(req.query.name||''),ok=auth(l,name,req.query.token);res.json({modes:l.poolModes,data:ok?(l.extraPools[name]||{}):{},players:Object.keys(l.users)})}));
app.post('/api/leagues/:id/extras',route(async(req,res)=>{const l=await getLeague(req.params.id),name=String(req.body.name||'');if(!l)return res.sendStatus(404);if(!auth(l,name,req.body.token))return res.status(403).json({error:'Please sign in again.'});extrasFor(l);l.extraPools[name]=l.extraPools[name]||{};const mode=String(req.body.mode||'');const allowed=['confidence','ats','lock','squares','doubleSurvivor','upset','playoffs','superBowl'];if(!allowed.includes(mode))return res.status(400).json({error:'Unknown pool mode'});l.extraPools[name][mode]=req.body.value||{};await putLeague(req.params.id,l);res.json({ok:true})}));
app.post('/api/leagues/:id/modes',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});extrasFor(l);for(const k of Object.keys(DEFAULT_MODES))if(k in (req.body.modes||{}))l.poolModes[k]=!!req.body.modes[k];await putLeague(req.params.id,l);res.json({ok:true,modes:l.poolModes})}));

// Live Game Center: refreshed scoreboard plus pool-wide live pick projections.
app.get('/api/leagues/:id/live',route(async(req,res)=>{
  const l=await getLeague(req.params.id); if(!l)return res.sendStatus(404);
  const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),now=Date.now();
  const rows=[];
  for(const [name,u] of Object.entries(l.users)){
    let correct=0,wrong=0,leading=0,pending=0;
    for(const g of games){
      const pick=u.picks?.[g.id]; if(!pick)continue;
      const win=l.manualResults[g.id]||g.winner;
      if(win){pick===win?correct++:wrong++;continue}
      const as=Number(g.awayScore),hs=Number(g.homeScore);
      if(Number.isFinite(as)&&Number.isFinite(hs)&&as!==hs){const leader=as>hs?g.away:g.home;pick===leader?leading++:pending++}else pending++;
    }
    rows.push({name,correct,wrong,leading,pending,projected:correct+leading});
  }
  rows.sort((a,b)=>b.projected-a.projected||b.correct-a.correct||a.wrong-b.wrong||a.name.localeCompare(b.name));
  res.json({week,updatedAt:new Date().toISOString(),refreshSeconds:15,games:games.map(g=>({...g,winner:l.manualResults[g.id]||g.winner,locked:Date.parse(g.kickoff)<=now})),standings:rows});
}));


// V8.3.4 Game Detail Center: live NFL matchup stats + pool impact after kickoff.
app.get('/api/leagues/:id/game/:gameId/details',route(async(req,res)=>{
  const l=await getLeague(req.params.id); if(!l)return res.sendStatus(404);
  const week=Math.max(1,Math.min(18,+req.query.week||3)), games=await schedule(week), g=games.find(x=>String(x.id)===String(req.params.gameId));
  if(!g)return res.status(404).json({error:'Game not found'});
  const now=Date.now(), locked=Date.parse(g.kickoff)<=now, winner=l.manualResults[g.id]||g.winner;
  let nfl={teamStats:[],leaders:[],plays:[],scoring:[]};
  try{
    const rr=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary?event=${encodeURIComponent(g.id)}`,{signal:AbortSignal.timeout(5000)});
    if(rr.ok){
      const j=await rr.json(), comp=j.header?.competitions?.[0];
      const boxes=j.boxscore?.teams||[];
      const statMap={};
      for(const t of boxes){const ab=t.team?.abbreviation; statMap[ab]={}; for(const x of (t.statistics||[]))statMap[ab][x.label||x.name]=x.displayValue??x.value??'—'}
      const labels=['First Downs','Total Yards','Passing Yards','Rushing Yards','Turnovers','Possession'];
      nfl.teamStats=labels.map(label=>({label,away:statMap[g.away]?.[label]??'—',home:statMap[g.home]?.[label]??'—'}));
      for(const group of (j.leaders||[]))for(const leader of (group.leaders||[]).slice(0,3)) nfl.leaders.push({category:group.name||group.displayName||'Leader',name:leader.athlete?.displayName||'—',team:leader.team?.abbreviation||'',value:leader.displayValue||''});
      nfl.plays=(j.plays||[]).slice(-30).reverse().map(x=>({
        id:x.id||'',text:x.text||'',clock:x.clock?.displayValue||'',period:x.period?.number||'',scoring:!!x.scoringPlay,
        type:x.type?.text||x.type?.abbreviation||'',team:x.team?.abbreviation||'',
        startYard:x.start?.yardLine??null,endYard:x.end?.yardLine??null,
        startText:x.start?.text||'',endText:x.end?.text||'',down:x.start?.down??null,distance:x.start?.distance??null,
        possession:x.start?.team?.abbreviation||x.team?.abbreviation||''
      }));
      nfl.scoring=(j.scoringPlays||[]).map(x=>({text:x.text||'',clock:x.clock?.displayValue||'',period:x.period?.number||'',team:x.team?.abbreviation||''}));
      if(comp){g.statusDetail=comp.status?.type?.detail||g.statusDetail;g.clock=comp.status?.displayClock||g.clock;g.period=comp.status?.period||g.period}
    }
  }catch(e){}
  const poolPicks=[]; let awayCount=0,homeCount=0;
  if(locked){for(const [name,u] of Object.entries(l.users||{})){const pick=u.picks?.[g.id]||null;if(!pick)continue;poolPicks.push({name,pick});pick===g.away?awayCount++:pick===g.home&&homeCount++}}
  const total=awayCount+homeCount;
  const as=Number(g.awayScore),hs=Number(g.homeScore),leader=Number.isFinite(as)&&Number.isFinite(hs)&&as!==hs?(as>hs?g.away:g.home):null;
  const impact=[];
  if(locked){for(const [name,u] of Object.entries(l.users||{})){const pick=u.picks?.[g.id];if(pick)impact.push({name,pick,state:winner?(pick===winner?'won':'lost'):leader?(pick===leader?'winning':'losing'):'tied'})}}
  res.json({game:{...g,winner,locked},nfl,pool:{revealed:locked,awayCount,homeCount,total,awayPct:total?Math.round(awayCount/total*100):0,homePct:total?Math.round(homeCount/total*100):0,picks:poolPicks,impact}});
}));

// V8.2 Notification Center. Local mode writes to an outbox; production can send with Resend when configured.
async function membershipsForLeague(leagueId){if(!pg)return (local.memberships||[]).filter(x=>x.league_id===leagueId);const r=await pg.query('SELECT * FROM memberships WHERE league_id=$1',[leagueId]);return r.rows}
async function sendReminderEmail(to,subject,html){
  if(process.env.RESEND_API_KEY){
    const from=String(process.env.EMAIL_FROM||'Fourth & Pick <onboarding@resend.dev>').trim();
    const replyTo=String(process.env.EMAIL_REPLY_TO||'').trim();
    const payload={from,to:[to],subject,html};
    if(replyTo)payload.reply_to=replyTo;
    const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});
    if(!r.ok){
      let detail='';
      try{const body=await r.json();detail=String(body?.message||body?.error||'').slice(0,300)}catch(e){try{detail=(await r.text()).slice(0,300)}catch(_) {}}
      throw new Error(`Email provider rejected message (${r.status})${detail?`: ${detail}`:''}`);
    }
    return {sent:true,provider:'resend',from,replyTo:replyTo||null};
  }
  const item={id:crypto.randomBytes(5).toString('hex'),to,subject,html,createdAt:new Date().toISOString(),provider:'local-preview'};
  local.emailOutbox=local.emailOutbox||[];local.emailOutbox.unshift(item);if(!pg)fs.writeFileSync(LOCAL_DB,JSON.stringify(local,null,2));return {sent:false,preview:true,id:item.id};
}
app.post('/api/account/preferences',route(async(req,res)=>{const a=await accountByToken(req.body.accountToken);if(!a)return res.status(401).json({error:'Please sign in.'});a.email=String(req.body.email||'').trim().toLowerCase().slice(0,160);a.email_reminders=req.body.emailReminders!==false;await saveAccount(a);res.json({ok:true,email:a.email,emailReminders:a.email_reminders})}));
app.get('/api/leagues/:id/reminders',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.query.pin))return res.status(403).json({error:'Wrong commissioner PIN'});const week=Math.max(1,Math.min(18,+req.query.week||3)),games=await schedule(week),members=await membershipsForLeague(req.params.id),rows=[];for(const [name,u] of Object.entries(l.users)){const missing=games.filter(g=>Date.parse(g.kickoff)>Date.now()&&!u.picks?.[g.id]).length;const m=members.find(x=>x.player_name===name);const a=m?await getAccount(m.account_id):null;rows.push({name,missing,email:a?.email||'',enabled:a?.email_reminders!==false,linked:!!a})}res.json({week,rows,outbox:!pg?(local.emailOutbox||[]).slice(0,12):[]})}));
app.post('/api/leagues/:id/reminders/send',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});const week=Math.max(1,Math.min(18,+req.body.week||3)),games=await schedule(week),members=await membershipsForLeague(req.params.id),results=[];for(const [name,u] of Object.entries(l.users)){const missing=games.filter(g=>Date.parse(g.kickoff)>Date.now()&&!u.picks?.[g.id]).length;if(!missing)continue;const m=members.find(x=>x.player_name===name),a=m?await getAccount(m.account_id):null;if(!a?.email||a.email_reminders===false){results.push({name,status:'skipped',reason:'No reminder email'});continue}const subject=`Fourth & Pick — ${missing} pick${missing===1?'':'s'} still needed for Week ${week}`;const link=String(req.body.baseUrl||'http://localhost:3000').replace(/\/$/,'')+`/?pool=${req.params.id}`;const html=`<div style="font-family:Arial;background:#061625;color:#fff;padding:24px"><h1>Fourth & Pick</h1><h2>Hey ${name}, your Week ${week} picks aren't finished.</h2><p>You still have <b>${missing}</b> unlocked pick${missing===1?'':'s'} to make.</p><p><a href="${link}" style="background:#169cff;color:white;padding:12px 18px;border-radius:8px;text-decoration:none;font-weight:bold">MAKE MY PICKS</a></p></div>`;const result=await sendReminderEmail(a.email,subject,html);results.push({name,email:a.email,status:result.sent?'sent':'preview'})}res.json({ok:true,results,mode:process.env.RESEND_API_KEY?'live-email':'local-preview'})}));

// V8.3 commissioner announcements, custom rules and audit trail.
app.get('/api/leagues/:id/v83-admin',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.query.pin))return res.status(403).json({error:'Wrong commissioner PIN'});res.json({announcement:l.announcement||'',rules:l.customRules||'',audit:l.auditLog||[]})}));
app.post('/api/leagues/:id/v83-admin',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});l.auditLog=l.auditLog||[];const announcement=String(req.body.announcement||'').trim().slice(0,180),rules=String(req.body.rules||'').trim().slice(0,4000);if(announcement!==String(l.announcement||''))l.auditLog.push({at:new Date().toISOString(),action:announcement?'Commissioner posted an announcement':'Commissioner cleared the announcement'});if(rules!==String(l.customRules||''))l.auditLog.push({at:new Date().toISOString(),action:'Commissioner updated pool rules'});l.announcement=announcement;l.customRules=rules;l.auditLog=l.auditLog.slice(-100);await putLeague(req.params.id,l);res.json({ok:true})}));

// V8.3.2 Commissioner Communications Center.
app.get('/api/leagues/:id/communications',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.query.pin))return res.status(403).json({error:'Wrong commissioner PIN'});const members=await membershipsForLeague(req.params.id),players=[];for(const [name] of Object.entries(l.users||{})){const m=members.find(x=>x.player_name===name),a=m?await getAccount(m.account_id):null;players.push({name,email:a?.email||'',linked:!!a})}res.json({players,posts:(l.poolPosts||[]).slice().reverse().slice(0,30),communications:(l.communicationLog||[]).slice().reverse().slice(0,40),outbox:!pg?(local.emailOutbox||[]).slice(0,20):[]})}));
app.post('/api/leagues/:id/communications/email',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});const subject=String(req.body.subject||'').trim().slice(0,140),message=String(req.body.message||'').trim().slice(0,6000);if(!subject||!message)return res.status(400).json({error:'Subject and message are required.'});const members=await membershipsForLeague(req.params.id),wanted=Array.isArray(req.body.players)?req.body.players.map(String):[],target=String(req.body.target||'all'),results=[];for(const [name] of Object.entries(l.users||{})){if(target==='specific'&&!wanted.includes(name))continue;const m=members.find(x=>x.player_name===name),a=m?await getAccount(m.account_id):null;if(!a?.email){results.push({name,status:'skipped'});continue}const safe=message.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c])).replace(/\n/g,'<br>');const html=`<div style="font-family:Arial;background:#061625;color:#fff;padding:26px"><h1>Fourth & Pick</h1><h2>${subject.replace(/[&<>]/g,'')}</h2><p>${safe}</p><p style="color:#9db4c8">Sent by the commissioner of ${String(l.name||'Fourth & Pick').replace(/[&<>]/g,'')}</p></div>`;const out=await sendReminderEmail(a.email,subject,html);results.push({name,email:a.email,status:out.sent?'sent':'preview'})}l.communicationLog=l.communicationLog||[];l.communicationLog.push({id:crypto.randomBytes(5).toString('hex'),at:new Date().toISOString(),type:'email',subject,message,target,count:results.filter(x=>x.status==='sent'||x.status==='preview').length});l.communicationLog=l.communicationLog.slice(-150);await putLeague(req.params.id,l);res.json({ok:true,results,mode:process.env.RESEND_API_KEY?'live-email':'local-preview'})}));
app.post('/api/leagues/:id/communications/post',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});const title=String(req.body.title||'').trim().slice(0,100),message=String(req.body.message||'').trim().slice(0,3000),priority=['normal','important','urgent'].includes(req.body.priority)?req.body.priority:'normal';if(!title||!message)return res.status(400).json({error:'Announcement title and message are required.'});l.poolPosts=l.poolPosts||[];const post={id:crypto.randomBytes(5).toString('hex'),title,message,priority,pinned:req.body.pinned!==false,createdAt:new Date().toISOString()};l.poolPosts.push(post);l.poolPosts=l.poolPosts.slice(-100);l.announcement=title+' — '+message.slice(0,120);l.communicationLog=l.communicationLog||[];l.communicationLog.push({id:post.id,at:post.createdAt,type:'post',subject:title,message,target:'pool',count:Object.keys(l.users||{}).length});if(req.body.alsoEmail){req.body.subject=title;req.body.message=message;}await putLeague(req.params.id,l);res.json({ok:true,post})}));
app.post('/api/leagues/:id/communications/post/:postId/delete',route(async(req,res)=>{const l=await getLeague(req.params.id);if(!l)return res.sendStatus(404);if(!adminOK(l,req.body.pin))return res.status(403).json({error:'Wrong commissioner PIN'});l.poolPosts=(l.poolPosts||[]).filter(x=>x.id!==req.params.postId);await putLeague(req.params.id,l);res.json({ok:true})}));
app.get('/health',route(async(req,res)=>{if(pg)await pg.query('SELECT 1');res.json({ok:true,version:'8.3.5-pool-membership',storage:pg?'postgresql':'local-json'})}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error. Please try again.'})});
const PORT=process.env.PORT||3000;initDB().then(()=>app.listen(PORT,()=>console.log(`Fourth & Pick V8.3.5 running on port ${PORT} (${pg?'PostgreSQL':'local JSON'} storage)`))).catch(e=>{console.error('Database startup failed:',e);process.exit(1)});
